#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import os
import tempfile
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", str(Path(tempfile.gettempdir()) / "matplotlib-cdi"))

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LinearSegmentedColormap, TwoSlopeNorm

plt.rcParams["font.family"] = "DejaVu Sans"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render CDI heatmaps from long-form CSV generated by build_cdi_table.py.")
    parser.add_argument("--input", required=True, help="Path to *_long.csv")
    parser.add_argument("--output", default="cdi_heatmap.png", help="Output image path")
    parser.add_argument("--material", default="Material", help="Title shown above the heatmap")
    parser.add_argument(
        "--value-field",
        default="cdi_100",
        choices=["cdi_raw", "cdi_100"],
        help="Which CDI field to visualize",
    )
    return parser.parse_args()


def to_float(value: str) -> float | None:
    if value is None:
        return None
    text = str(value).strip().replace(",", ".")
    if text == "":
        return None
    try:
        return float(text)
    except ValueError:
        return None


def format_number(value: float) -> str:
    text = f"{value:.3f}"
    return text.rstrip("0").rstrip(".")


def load_long_csv(path: Path, value_field: str) -> tuple[list[str], list[dict[str, float]]]:
    records: list[dict[str, float]] = []
    cell_line_order: list[str] = []
    seen: set[str] = set()

    with path.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            cell_line = row["cell_line"]
            dose = to_float(row["dose_gy"])
            concentration = to_float(row["concentration_mg_ml"])
            value = to_float(row[value_field])
            if dose is None or concentration is None or value is None:
                continue
            if abs(dose) < 1e-9 or abs(concentration) < 1e-9:
                continue
            if cell_line not in seen:
                seen.add(cell_line)
                cell_line_order.append(cell_line)
            records.append(
                {
                    "cell_line": cell_line,
                    "dose": dose,
                    "concentration": concentration,
                    "value": value,
                }
            )
    return cell_line_order, records


def build_matrix(records: list[dict[str, float]], cell_line: str) -> tuple[list[float], list[float], np.ndarray]:
    subset = [row for row in records if row["cell_line"] == cell_line]
    doses = sorted({row["dose"] for row in subset})
    concentrations = sorted({row["concentration"] for row in subset}, reverse=True)
    matrix = np.full((len(concentrations), len(doses)), np.nan, dtype=float)
    conc_index = {value: idx for idx, value in enumerate(concentrations)}
    dose_index = {value: idx for idx, value in enumerate(doses)}

    for row in subset:
        matrix[conc_index[row["concentration"]], dose_index[row["dose"]]] = row["value"]
    return doses, concentrations, matrix


def render_heatmap(input_path: Path, output_path: Path, material: str, value_field: str) -> None:
    cell_lines, records = load_long_csv(input_path, value_field)
    if not records:
        raise RuntimeError(f"No numeric {value_field} values found in {input_path}")

    matrices = [build_matrix(records, cell_line) for cell_line in cell_lines]
    values = np.concatenate([matrix[np.isfinite(matrix)] for _, _, matrix in matrices])
    vmin = min(0.55, float(values.min()))
    vmax = max(1.45, float(values.max()))
    norm = TwoSlopeNorm(vmin=vmin, vcenter=1.0, vmax=vmax)
    cmap = LinearSegmentedColormap.from_list(
        "cdi",
        [
            (0.00, "#5aa66a"),
            (0.33, "#b9ddb2"),
            (0.50, "#f6e0ab"),
            (0.72, "#efbf9a"),
            (1.00, "#d95a58"),
        ],
    )

    single_panel = len(cell_lines) == 1
    fig_width = 6.8 if single_panel else (5.1 * len(cell_lines) + 1.6)
    fig = plt.figure(figsize=(fig_width, 4.4), facecolor="white")
    if single_panel:
        axes = [fig.add_axes([0.18, 0.18, 0.56, 0.62])]
        cbar_ax = fig.add_axes([0.69, 0.26, 0.030, 0.48])
    else:
        grid = fig.subplots(1, len(cell_lines), sharey=True)
        axes = [grid] if len(cell_lines) == 1 else list(grid)
        cbar_ax = fig.add_axes([0.90, 0.22, 0.018, 0.56])

    last_image = None
    for index, (ax, cell_line, payload) in enumerate(zip(axes, cell_lines, matrices)):
        doses, concentrations, matrix = payload
        image = ax.imshow(matrix, cmap=cmap, norm=norm, interpolation="nearest")
        last_image = image

        ax.set_title(cell_line, fontsize=15, fontweight="bold", pad=8)
        ax.set_xticks(range(len(doses)))
        ax.set_xticklabels([format_number(value) for value in doses], fontsize=11)
        ax.set_xlabel("Доза, Гр", fontsize=12)
        ax.set_yticks(range(len(concentrations)))
        ax.set_yticklabels([format_number(value) for value in concentrations], fontsize=11)
        if index == 0:
            ax.set_ylabel("Конц., мг/мл", fontsize=12)
        else:
            ax.tick_params(axis="y", labelleft=False)

        ax.set_aspect("equal")
        ax.tick_params(axis="both", length=3.5, width=0.9, colors="#333333", pad=3)

        for row in range(matrix.shape[0]):
            for col in range(matrix.shape[1]):
                value = matrix[row, col]
                if np.isfinite(value):
                    ax.text(col, row, f"{value:.3f}", ha="center", va="center", fontsize=10, color="black")

        for spine in ax.spines.values():
            spine.set_linewidth(0.85)
            spine.set_color("#333333")

    cbar = fig.colorbar(last_image, cax=cbar_ax)
    ticks = [tick for tick in (0.7, 1.0, 1.3) if vmin <= tick <= vmax]
    if not ticks:
        ticks = [float(values.min()), 1.0, float(values.max())]
    cbar.set_ticks(ticks)
    tick_labels = []
    for tick in ticks:
        if abs(tick - 0.7) < 1e-6:
            tick_labels.append("0.7 (синергия)")
        elif abs(tick - 1.0) < 1e-6:
            tick_labels.append("1 (аддитивность)")
        elif abs(tick - 1.3) < 1e-6:
            tick_labels.append("1.3 (антагонизм)")
        else:
            tick_labels.append(format_number(tick))
    cbar.set_ticklabels(tick_labels)
    cbar.ax.tick_params(labelsize=11, length=3.0, width=0.8, colors="#333333")
    cbar.outline.set_linewidth(0.8)
    cbar.set_label("CDI", fontsize=12, rotation=90, labelpad=10)

    fig.suptitle(material, fontsize=19, fontweight="bold", y=0.95)
    if not single_panel:
        fig.subplots_adjust(left=0.12, right=0.86, bottom=0.18, top=0.84, wspace=0.34)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=180, facecolor="white", bbox_inches="tight", pad_inches=0.08)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    render_heatmap(Path(args.input), Path(args.output), args.material, args.value_field)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
